# Type hints for Kivy components used in the project
from typing import Any, Callable, Optional, Union, List, Dict
from typing_extensions import ParamSpec

P = ParamSpec('P')

class NumericProperty:
    def __init__(self, defaultvalue: Union[int, float] = 0, **kw: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = None) -> Union[int, float]: ...
    def __set__(self, obj: Any, val: Union[int, float]) -> None: ...

class StringProperty:
    def __init__(self, defaultvalue: str = '', **kw: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = None) -> str: ...
    def __set__(self, obj: Any, val: str) -> None: ...

class BooleanProperty:
    def __init__(self, defaultvalue: bool = False, **kw: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = None) -> bool: ...
    def __set__(self, obj: Any, val: bool) -> None: ...

class ListProperty:
    def __init__(self, defaultvalue: Optional[List[Any]] = None, **kw: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = None) -> List[Any]: ...
    def __set__(self, obj: Any, val: List[Any]) -> None: ...

class DictProperty:
    def __init__(self, defaultvalue: Optional[Dict[str, Any]] = None, **kw: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = None) -> Dict[str, Any]: ...
    def __set__(self, obj: Any, val: Dict[str, Any]) -> None: ...

class ObjectProperty:
    def __init__(self, defaultvalue: Any = None, **kw: Any) -> None: ...
    def __get__(self, obj: Any, objtype: Optional[type] = None) -> Any: ...
    def __set__(self, obj: Any, val: Any) -> None: ...

class Widget:
    def __init__(self, **kwargs: Any) -> None: ...
    def bind(self, **kwargs: Callable[..., Any]) -> None: ...
    def unbind(self, **kwargs: Callable[..., Any]) -> None: ...
    def fbind(self, name: str, func: Callable[..., Any], *largs: Any, **kwargs: Any) -> None: ...
    def funbind(self, name: str, func: Callable[..., Any], *largs: Any, **kwargs: Any) -> None: ...
    def on_touch_down(self, touch: Any) -> bool: ...
    def on_touch_move(self, touch: Any) -> bool: ...
    def on_touch_up(self, touch: Any) -> bool: ...

class Screen(Widget):
    name: str
    manager: Optional['ScreenManager']
    def on_enter(self) -> None: ...
    def on_leave(self) -> None: ...
    def on_pre_enter(self, *args: Any) -> None: ...
    def on_pre_leave(self, *args: Any) -> None: ...

class ScreenManager(Widget):
    current: str
    transition: Any
    screens: List[Screen]
    def add_widget(self, screen: Screen) -> None: ...
    def get_screen(self, name: str) -> Screen: ...

class Button(Widget):
    text: str
    on_release: Callable[[], None]
    on_press: Callable[[], None]
    def bind(self, on_release: Optional[Callable[[], None]] = None, 
             on_press: Optional[Callable[[], None]] = None, **kwargs: Any) -> None: ...

class Label(Widget):
    text: str
    markup: bool
    size_hint_y: Optional[float]
    height: Union[int, float]

class Builder:
    @staticmethod
    def load_file(filename: str, **kwargs: Any) -> Optional[Widget]: ...
    @staticmethod  
    def load_string(string: str, **kwargs: Any) -> Optional[Widget]: ...