"""
This type stub file was generated by pyright.
"""

from kivy.uix.behaviors import ToggleButtonBehavior
from kivy.uix.widget import Widget

'''
CheckBox
========

.. versionadded:: 1.4.0

.. image:: images/checkbox.png
    :align: right

:class:`CheckBox` is a specific two-state button that can be either checked or
unchecked. If the CheckBox is in a Group, it becomes a Radio button.
As with the :class:`~kivy.uix.togglebutton.ToggleButton`, only one Radio button
at a time can be selected when the :attr:`CheckBox.group` is set.

An example usage::

    from kivy.uix.checkbox import CheckBox

    # ...

    def on_checkbox_active(checkbox, value):
        if value:
            print('The checkbox', checkbox, 'is active')
        else:
            print('The checkbox', checkbox, 'is inactive')

    checkbox = CheckBox()
    checkbox.bind(active=on_checkbox_active)
'''
__all__ = ('CheckBox', )
class CheckBox(ToggleButtonBehavior, Widget):
    '''CheckBox class, see module documentation for more information.
    '''
    active = ...
    background_checkbox_normal = ...
    background_checkbox_down = ...
    background_checkbox_disabled_normal = ...
    background_checkbox_disabled_down = ...
    background_radio_normal = ...
    background_radio_down = ...
    background_radio_disabled_normal = ...
    background_radio_disabled_down = ...
    color = ...
    def __init__(self, **kwargs) -> None:
        ...
    
    def on_group(self, *largs): # -> None:
        ...
    


if __name__ == '__main__':
    x = ...
